import controle.dominio.*;
import controle.agente.atuador.*

global controle.agente.atuador.ControladorAtuacao controladorAtuacao;

rule "filaMensagensAtiva"
	activation-group "reconfiguracao"
when 
	$elemento : Atributo(identificador == IdentificadorAtributoElementoGerenciado.NUMERO_MENSAGENS 
							&& programa.identificador == IdentificadorElementoGerenciado.FILA_MENSAGEM 
							&& estadoAtual == Estado.NORMAL);
then
	System.out.println("REGRA ATIVADA - NORMAL! " + $elemento.toString());
end

rule "filaMensagensEmAlerta"
	activation-group "reconfiguracao"
when 
	$elemento : Atributo(identificador == IdentificadorAtributoElementoGerenciado.NUMERO_MENSAGENS 
							&& programa.identificador == IdentificadorElementoGerenciado.FILA_MENSAGEM 
							&& estadoAtual == Estado.ALERTA);
then
	System.out.println("REGRA ATIVADA - ALERTA! " + $elemento.toString());
	//controladorAtuacao.ruleFired(AgenteInicializadorInstanciaExecutor.class, "EXECUTOR_INSTANCIA_2");
end

rule "filaMensagensCritica"
	activation-group "reconfiguracao"
when 
	$elemento : Atributo(identificador == IdentificadorAtributoElementoGerenciado.NUMERO_MENSAGENS 
							&& programa.identificador == IdentificadorElementoGerenciado.FILA_MENSAGEM 
							&& estadoAtual == Estado.CRITICO);
then
	System.out.println("REGRA ATIVADA - CRITICO! " + $elemento.toString());
end
