import controle.evento.*;
import controle.dominio.*;
import controle.agente.atuador.*

declare EventoNumeroMensagensFila
	@role( event )
	@expires( 1s )
end

rule "estadoAtivoFilaMensagens"
	activation-group "atualizacao-fila"
	no-loop true
when 
	$evento : EventoNumeroMensagensFila(numeroMensagensFila <= 100)
	from entry-point "FluxoDeEventos"
	$elemento : Atributo(identificador == IdentificadorAtributoElementoGerenciado.NUMERO_MENSAGENS 
							&& programa.identificador == IdentificadorElementoGerenciado.FILA_MENSAGEM);
then
	modify ($elemento) {
		setEstadoAtual(Estado.NORMAL);
	}
end

rule "estadoAlertaFilaMensagens"
	activation-group "atualizacao-fila"
	no-loop true
when 
	$evento : EventoNumeroMensagensFila(numeroMensagensFila > 100 && numeroMensagensFila <= 200)
	from entry-point "FluxoDeEventos"
	$elemento : Atributo(identificador == IdentificadorAtributoElementoGerenciado.NUMERO_MENSAGENS 
							&& programa.identificador == IdentificadorElementoGerenciado.FILA_MENSAGEM);
then
	modify ($elemento) {
		setEstadoAtual(Estado.ALERTA);
	}
end

rule "estadoCriticoFilaMensagens"
	activation-group "atualizacao-fila"
	no-loop true
when 
	$evento : EventoNumeroMensagensFila(numeroMensagensFila > 200)
	from entry-point "FluxoDeEventos"
	$elemento : Atributo(identificador == IdentificadorAtributoElementoGerenciado.NUMERO_MENSAGENS 
							&& programa.identificador == IdentificadorElementoGerenciado.FILA_MENSAGEM);
then
	modify ($elemento) {
		setEstadoAtual(Estado.CRITICO);
	}
end
