import controle.evento.*;
import controle.dominio.*;
import controle.agente.atuador.*

global controle.agente.atuador.ControladorAtuacao controladorAtuacao;

declare EventoNumeroMensagensFila
	@role( event )
	@expires( 2s )
end

rule numeroMaximoMensagens
when 
	$evento : EventoNumeroMensagensFila(numeroMensagensFila > 100)
	from entry-point "FluxoDeEventos"
then
	AtributoElementoGerenciado elemento = new AtributoElementoGerenciado($evento.getIdentificador(), Estado.ATIVO);
	insert(elemento);
	controladorAtuacao.ruleFired(AgenteInicializadorInstanciaExecutor.class, "EXECUTOR_INSTANCIA_2");
end

rule numeroMinimoMensagens
when 
	$evento : EventoNumeroMensagensFila(numeroMensagensFila < 100)
	from entry-point "FluxoDeEventos"
then
	AtributoElementoGerenciado elemento = new AtributoElementoGerenciado($evento.getIdentificador(), Estado.ATIVO);
	insert(elemento);
	controladorAtuacao.ruleFired(AgenteInterruptorInstanciaExecutor.class, "EXECUTOR_INSTANCIA_2");
end

rule atualizaEstadoElementoFila
when 
    $evento : EventoNumeroMensagensFila(identificador != null)
	from entry-point "FluxoDeEventos"
	$elemento : AtributoElementoGerenciado(identificador == $evento.getIdentificador());
then
	$elemento.setEstado(Estado.ATIVO);
end