import controle.evento.*;
import controle.dominio.*;

global controle.agente.atuador.ControladorAtuacao controladorAtuacao;

declare EventoNumeroMensagensFila
	@role( event )
	@expires( 2s )
end

rule numeroMaximoMensagens
when 
	$evento : EventoNumeroMensagensFila(numeroMensagensFila > 10)
	from entry-point "FluxoDeEventos"
then
	AtributoElementoGerenciado elemento = new AtributoElementoGerenciado($evento.getIdentificador(), Estado.ATIVO);
	insert(elemento);
	controladorAtuacao.ruleFired();
end


rule atualizaEstadoElementoFila
when 
    $evento : EventoNumeroMensagensFila(identificador != null)
	from entry-point "FluxoDeEventos"
	$elemento : AtributoElementoGerenciado(identificador == $evento.getIdentificador());
then
	$elemento.setEstado(Estado.ATIVO);
end